HW 2 Done
Clojure-Developer/Clojure-Developer-2023-10 pull request #13
Opened 2023-11-26 21:58 UTC by skylightis666

Лично мне не нравится функция `convert-string-to-mass`, хотел чтобы в неё можно было передавать функцию, которая как-либо преобразует строку в конце, а получилось передать только символ и это привело к интересному багу, потому что если передавать символ в тестах с алиасом неймспейса у символа, то он падает. Почему я не смог сделать нормально -- загадка)

2023-11-29 21:24 UTC, margintop15px commented on otus-02/src/otus_02/homework/palindrome.clj
> +             (partial (resolve case-fun))))))
не совсем понятно для чего тут `partial`?
кажется можно просто функцию вернуть

2023-11-29 21:49 UTC, margintop15px commented on otus-02/src/otus_02/homework/square_code.clj
> +                                         )))]
хорошая попытка сделать через loop 👍 
еще можно попробовать сделать через коллекции, например разбить строку на кусочки длинной rows и сделать двумерный вектор а потом применить все кусочки к map `(apply map str rows-vector)`
будет более идеоматично

2023-11-30 18:13 UTC, skylightis666 commented on otus-02/src/otus_02/homework/square_code.clj
> +                                         )))]
Попробую, иногда просто посещают мысли об оптимизациях а-ля "зачем мне трансформировать одномерный массив к двумерному,  если я и так по нему могу пройтись, если мозг напрягу", но понятно, что это вредно, когда пишешь в команде или просто возвращаешься к коду в попытках понять написанное.

2023-12-01 07:29 UTC, astynax commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +        (= elem (get-in matrix [i j])))) ;;is copy-paste of (get-in acc [i j]) ok, or need to use let?
Стоит вынести в let. И читать проще будет, и лишний раз в вектор векторов ходить не будете, пусть это и не дорого.

2023-12-01 07:30 UTC, astynax commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +                      :down  {:i 1 :j 0}}]
Выглядит как константа, которую можно вынести на верхний уровень модуля, чтобы не воссоздавать каждый раз.

2023-12-01 07:32 UTC, astynax commented on otus-04/src/otus_04/homework/crossword_puzzle.clj
> +        (loop [i 0
Вижу loop, но не вижу recur.

2023-12-26 12:14 UTC, skylightis666 commented
Добавлены домашки по 6 и 8 занятию, ошибка в последнем commit message, там работа по 8 тестам к url-shortener

2024-01-01 07:43 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +             (into [])
Зачем здесь накапливать в вектор, если вы всё равно ниже делаете map? Который а) вполне переваривает line-seq и б) сам производит seq. В итоге всё содержимое файла сохраняется в промежуточном векторе и будет в нём храниться, пока вы не закончите работать с выходной последовательностью.

2024-01-01 07:53 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +
Вы здесь фактически выполняете все доступные действия. Даже если пользователь программы так и не попросит ничего сделать и сразу завершит работу. К тому же функции `calculate-income-by-client-name` и `get-sales-view` каждая заново вычитывают входные файлы, которые уже вычитали функции `load-customer` и `load-product`.

Если уж вы хотите все дайствия выполнить заранее, то имеет смысл сохранить в defs *результаты* чтения всех файлов, а в функциях, оперирующих этими данными, файлы вообще не трогать.

Но я лично, как потенциальный пользователь программы, ожидал бы, что она

- не будет читать никакие файлы, пока я не попрошу;
- будет читать файлы каждый раз, как я попрошу (файлы могут быть изменены, пока программа работает, и я могу захотеть увидеть изменения);
- будет читать только нужные в данный момент файлы.

2024-01-01 07:54 UTC, astynax requested changes
По HW#6 оставил пару замечаний.

2024-01-18 22:03 UTC, skylightis666 commented on otus-06/src/otus_06/homework.clj
> +
Поправил, не знаю что меня подтолкнуло делать вызовы прям в def... Был простой план сделать список функций, а дальше уже независимо их дёргать, не имелась ввиду никакая мемоизация, а даже наоборот, хотелось чтобы можно было апдейтить "базу" в ходе работы программы и получать соответствующие результаты.

2024-01-18 22:07 UTC, skylightis666 commented on otus-06/src/otus_06/homework.clj
> +             (into [])
А тут как раз всё просто, я просто не до конца тогда понимал как работает ленивость, а эмпирическим путём на AoC выяснил, что так норм читать файлы) Сделал через doall, так получше?

2024-01-19 05:28 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +              print-hint])
Я бы функции и описание в парах сразу хранил: так всегда будет сохраняться соответствие индекса, описания и функции. И "меню" можно выводить, обходя этот самый список пар и выводя только описания и индексы.

2024-01-19 05:31 UTC, astynax commented
По HW #6 ставлю "зачёт", теперь хорошо смотрится!

2024-01-19 05:36 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +                     (str/join "|" val))))
Я бы тут всё же более конкретные исключения ловил. Причём можно по идее обобщить такое построение specs из функций, кидающих исключения: пусть это будет "комбинатор", принимающий функцию, кидающую исключения, и перечень исключений, которые нужно считать ошибками валидации.

2024-01-19 05:43 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +    (trampoline choose-action))
Тут трамплин к месту! Состояние хранить не нужно между вызовами в том числе и в замыканиях, а с трамплином и loop/recur можно не писать :)

2024-01-19 05:48 UTC, astynax commented on otus-06/src/otus_06/homework.clj
> +        (assoc trg-kw ((comp src-kw first)
Не стоит использовать композицию функций, если вы тут же оную используете. Всё же comp - средство для описания функций "на будущее", а по месту лучше написать `(src-kw (first ...))`,

2024-01-19 14:48 UTC, closed without merging